---
# Couple notes:
#
# - ansible.builtin.shell uses /bin/sh by default
#   and nothing seems to be loaded
# - if the fish executable is used for the shell,
#   then .config/fish/config.fish is loaded
#

- name: "Pop_OS machine setup"
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    python_version: "3.12"
    node_version: "20"  # Until 2026, then 24 or 26 LTS installed
    fish_path: /usr/bin/fish
  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ ansible_env }}"

    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_user_id }}"

    - name: Install packages
      become: true
      ansible.builtin.apt:
        cache_valid_time: 3600
        name:
          # Development
          - build-essential
          - libxml2-dev
          - libxslt-dev
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - tk-dev
          - curl
          - emacs-nox
          - liblzma-dev
          - git-core
          - fonts-hack-ttf
          # Alternative package installer
          - gdebi-core
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          # Python
          - python3-apt
          - python3-venv
          - python3-pip
          - python3-gpg
          # Nice tools
          - zoxide
          - pdftk
          - imagemagick
          # Misc
          - gnome-tweaks
        state: present
      tags:
        - packages

    - name: Create folder structure
      block:
        - name: ~/bin folder
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/bin"
            state: directory

        - name: ~/dev folder
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/dev"
            state: directory

        - name: Packages folder
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/Downloads/Packages"
            state: directory
        - name: Set 'packages_dir' variable
          ansible.builtin.set_fact:
            packages_dir: "{{ ansible_env.HOME }}/Downloads/Packages"

    - name: Install VSCode
      block:
        - name: Download VSCode deb
          ansible.builtin.get_url:
            url: 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'
            dest: "{{ packages_dir }}/code.deb"

        - name: Install VSCode deb
          become: yes
          command:
            cmd: apt install -y {{ packages_dir }}/code.deb

        - name: Prefer official PPA over Pop_OS ppa
          become: yes
          blockinfile:
            create: true
            path: /etc/apt/preferences.d/vscode-settings
            block: |
              # Prefer vscode from the microsoft repo
              Package: code
              Pin: origin packages.microsoft.com
              Pin-Priority: 1002

    - name: Install mise
      block:
        - name: Import PUB Key
          become: yes
          ansible.builtin.get_url:
            url: https://mise.jdx.dev/gpg-key.pub
            dest: /etc/apt/keyrings/mise-archive-keyring

        - name: GPG dearmor
          become: yes
          ansible.builtin.shell:
            cmd: gpg --yes --dearmor < /etc/apt/keyrings/mise-archive-keyring > /etc/apt/keyrings/mise-archive-keyring.gpg

        - name: Add ppa
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg] https://mise.jdx.dev/deb stable main"
            state: present

        - name: Install
          become: true
          ansible.builtin.apt:
            name: mise
            state: present

   - name: Install zellij
     block:
       - name: Download zellij prebuilt binary
         ansible.builtin.get_url:
           url: https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz
           dest: "{{ ansible_env.HOME }}/Downloads/Packages"

       - name: Extract zellij
         ansible.builtin.unarchive:
           src: "{{ ansible_env.HOME }}/Downloads/Packages/zellij-x86_64-unknown-linux-musl.tar.gz"
           dest: "{{ ansible_env.HOME }}/bin"
           # extra_opts: [--strip-components=1]
           creates: "{{ ansible_env.HOME }}/bin/zellij"

       - name: Make zellij script executable
         ansible.builtin.file:
           path: "{{ ansible_env.HOME }}/bin/zellij"
           mode: '+x'
     tags:
       - zellij

    - name: Setup fish
      block:
        - name: Add fish ppa
          become: true
          ansible.builtin.apt_repository:
            repo: ppa:fish-shell/release-3

        - name: Install fish
          become: true
          ansible.builtin.apt:
            name: fish
            state: present

        - name: Install sharship prompt
          block:
            - name: Download starship install script
              ansible.builtin.get_url:
                url: https://starship.rs/install.sh
                dest: /tmp/starship_install.sh

            - name: Make starship install script executable
              ansible.builtin.file:
                path: /tmp/starship_install.sh
                mode: '+x'

            - name: Run starship install script
              become: true
              ansible.builtin.shell:
                cmd: /tmp/starship_install.sh --yes

        - name: Change shell to fish
          become: true
          ansible.builtin.user:
            name: "{{ remote_regular_user }}"
            shell: "{{ fish_path }}"

        - name: Check if fisher installed
          ansible.builtin.shell:
            cmd: fisher --version
            executable: "{{ fish_path }}"
          register: fisher_installed
          ignore_errors: true

        - name: Install fisher
          when: fisher_installed is failed
          ansible.builtin.shell:
            cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
            executable: "{{ fish_path }}"

    - name: Setup Python
      block:
        - name: Check if pyenv is installed
          ansible.builtin.shell:
            cmd: bash -lc "pyenv --version"
          register: pyenv_installed
          ignore_errors: true
          changed_when: false  # what does it do?

        - name: Install pyenv because not installed
          when: pyenv_installed is failed
          ansible.builtin.shell:
            cmd: curl https://pyenv.run | bash

        - name: Write required .profile changes
          ansible.builtin.blockinfile:
            path: ~/.profile
            block: |
              export PYENV_ROOT="$HOME/.pyenv"
              [[ -d $PYENV_ROOT/bin ]] && export PATH=$PYENV_ROOT/bin:$PATH
              eval "$(pyenv init -)"

        - name: Install Python {{ python_version }}
          when: pyenv_installed is failed
          ansible.builtin.shell:
            cmd: pyenv install {{ python_version }}
          register: python_installed

        - name: Set python {{ python_version }} as the global version
          when: pyenv_installed is failed
          ansible.builtin.shell:
            cmd: pyenv global {{ python_version}}

        - name: Upgrade pip
          ansible.builtin.shell:
            cmd: pip install --upgrade pip
          become: true

        # Only for Ubuntu 22.04 and below, but should be fine for above too
        - name: Install pipx
          ansible.builtin.shell:
            cmd: python3 -m {{ item }}
          with_items:
            - pip install --user pipx

        - name: Install pipenv
          ansible.builtin.shell:
            cmd: bash -lc "pipx install pipenv"

        - name: Install poetry
          ansible.builtin.shell:
            cmd: pipx install poetry

    - name: Install node (and npm)
      block:
        - name: Check if node installed
          ignore_errors: true
          ansible.builtin.shell:
            cmd: node --version
            executable: "{{ fish_path }}"
          register: node_installed

        - name: Install Node {{ node_version }}
          when: node_installed is failed
          ansible.builtin.shell:
            cmd: |
              mise use --global node@{{ node_version }}

    # - name: Install cargo
    #   ansible.builtin.shell:
    #     cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y
    #     warn: false

    - name: Install git-split-diffs
      ansible.builtin.shell:
        cmd: npm install -g git-split-diffs
        executable: "{{ fish_path }}"

    - name: Install gh
      block:
        - name: Import GPG Key
          ansible.builtin.get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /usr/share/keyrings/githubcli-archive-keyring.gpg

        - name: Get architecture
          ansible.builtin.command:
            cmd: dpkg --print-architecture
          register: architecture_out

        - ansible.builtin.set_fact:
            architecture: "{{ architecture_out.stdout }}"

        - name: Add ppa
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
            state: present

        - name: Install
          become: true
          ansible.builtin.apt:
            name: gh
            state: present

    # TODO: install docker
    # - name: Install Docker
    #   block:
    #     - name: Import Docker GPG key
    #       ansible.builtin.get_url:
    #         url: https://download.docker.com/linux/ubuntu/gpg
    #         dest: /etc/apt/trusted.gpg.d/docker.asc
    #         # TODO: add correct checksum
    #         # checksum: sha256:bb42f0db45d46bab5f9ec619e1a47360b94c27142e57aa71f7050d08672309e0

    #     - name: Add Docker ppa
    #       ansible.builtin.apt_repository:
    #         # or UBUNTU_CODENAME
    #         repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable"
    #         state: present

        # - name: Install docker
        #   ansible.builtin.apt:
        #     name: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        #     state: present

        # - name: Add Docker group
        #   ansible.builtin.group:
        #     name: docker
        #     state: present

        # - name: Add user to docker group
        #   ansible.builtin.user:
        #     name: "{{ remote_regular_user }}"
        #     groups: docker
        #     append: true

    # Install ulauncher - START
    # commented out for now since pop_os may have launcher already
    # - name: Add ulauncher ppa
    #   ansible.builtin.apt_repository:
    #     repo: ppa:agornostal/ulauncher

    # - name: Install ulauncher
    #   ansible.builtin.apt:
    #     name: ulauncher
    #     state: present
    # Install ulauncher - END

    # sudo apt autoremove

    # LEFTOVERS

    # - name: Add Brave Browser Repo
    #   ansible.builtin.yum_repository:
    #     name: brave-browser
    #     description: Brave Browser
    #     baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
    #     gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    #     gpgcheck: true
    #     enabled: true

    # - name: Import Brave Browser GPG Key
    #   ansible.builtin.rpm_key:
    #     key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    #     state: present

    # - name: Install Brave Browser
    #   ansible.builtin.dnf:
    #     name: brave-browser
    #     state: present

    - name: Install Synology Drive Client
      block:
        - name: Download client
          ansible.builtin.get_url:
            url: https://global.synologydownload.com/download/Utility/SynologyDriveClient/3.4.0-15724/Ubuntu/Installer/synology-drive-client-15724.x86_64.deb
            dest: "{{ ansible_env.HOME }}/Downloads/Packages"

        - name: Install client
          become: true
          ansible.builtin.apt:
            deb: "{{ ansible_env.HOME }}/Downloads/Packages/synology-drive-client-15724.x86_64.deb"

        - name: Launch Synology Drive client reminder
          ansible.builtin.debug:
            msg: "Don't forget to launch Synology Drive at least once to set it up!"
