add_newline = false
format = """
$time\
$directory\
$git_branch\
$python\
$line_break\
$character"""

[character]
success_symbol = ">"
error_symbol = ">"

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "⎇  "

[time]
disabled = false
format = "[$time]($style) "
